spring.application.name=products-service
server.port=8082
management.endpoints.jmx.exposure.include=*
spring.config.import=optional:classpath:application-services.properties,optional:file:products_service/.env[.properties]

# Details for our datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:product_db}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD}

# Hibernate properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator (healthcheck for Docker)
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
